import React,{useCallback,useState} from 'react';
import {Alert,ScrollView,StyleSheet,Text,View} from 'react-native';
import {useFocusEffect} from 'expo-router';
import {AppButton,AppInput,Card,NoAccess,SectionTitle} from '../../src/components/controls';
import {BackHeader,GradientScreen,KeyboardScreen} from '../../src/components/layout';
import {OptionPicker} from '../../src/components/pickers';
import {useSession} from '../../src/lib/session';
import {getSupabase} from '../../src/lib/supabase';
import {isOwner} from '../../src/lib/staff';
import {colors,font,spacing,themedStyles} from '../../src/theme';

type Staff={id:string;full_name:string;role:string};
export default function Accounting(){
 const {profile}=useSession(); const [rows,setRows]=useState<any[]>([]); const [staff,setStaff]=useState<Staff[]>([]);
 const [kind,setKind]=useState<'income'|'expense'>('expense'); const [entryType,setEntryType]=useState('general'); const [employee,setEmployee]=useState<string|null>(null);
 const [category,setCategory]=useState(''); const [desc,setDesc]=useState(''); const [amount,setAmount]=useState('');
 const load=useCallback(async()=>{if(!profile?.center_id)return;const sb=getSupabase();const [{data:r},{data:s}]=await Promise.all([sb.from('center_ledger').select('*').eq('center_id',profile.center_id).order('occurred_on',{ascending:false}).limit(200),sb.from('profiles').select('id,full_name,role').eq('center_id',profile.center_id).in('role',['teacher','manager','secretary'])]);setRows(r??[]);setStaff(s??[])},[profile?.center_id]); useFocusEffect(useCallback(()=>{void load()},[load]));
 if(!isOwner(profile))return <GradientScreen><BackHeader title="الحسابات"/><NoAccess message="قسم الحسابات متاح لصاحب السنتر فقط."/></GradientScreen>;
 const save=async()=>{const n=Number(amount);if(!category.trim()||!n||n<=0)return Alert.alert('بيانات ناقصة','أدخل التصنيف والمبلغ الصحيح');if(kind==='income')return Alert.alert('تنبيه','إيرادات الطلاب تُسجل تلقائياً من قسم التحصيل');const emp=staff.find(x=>x.id===employee);const {error}=await getSupabase().from('center_ledger').insert({center_id:profile!.center_id,kind,entry_type:entryType,category:category.trim(),description:desc.trim(),amount:n,employee_id:employee,created_by:profile!.id,created_by_name:profile!.full_name??''});if(error)Alert.alert('تعذر الحفظ',error.message);else{setCategory('');setDesc('');setAmount('');setEmployee(null);await load();Alert.alert('تم الحفظ',emp?`تم تسجيل الحركة على ${emp.full_name}`:'تم تسجيل المصروف')}};
 const income=rows.filter(r=>r.kind==='income').reduce((s,r)=>s+Number(r.amount),0), expense=rows.filter(r=>r.kind==='expense').reduce((s,r)=>s+Number(r.amount),0);
 const collectorTotals=Object.entries(rows.filter(r=>r.entry_type==='payment_collection').reduce((a:any,r:any)=>{const k=r.created_by_name||'غير معروف';a[k]=(a[k]||0)+Number(r.amount);return a},{}));
 const employeeTotals=Object.entries(rows.filter(r=>r.kind==='expense'&&r.employee_id).reduce((a:any,r:any)=>{const k=r.employee_id;a[k]=(a[k]||0)+Number(r.amount);return a},{}));
 return <GradientScreen><BackHeader title="الحسابات" subtitle="دفتر مالي احترافي للسنتر"/><KeyboardScreen><Card><View style={styles.summary}><Stat t="الإيرادات" v={income}/><Stat t="المصروفات" v={expense}/><Stat t="الصافي" v={income-expense}/></View></Card><SectionTitle title="إضافة مصروف / راتب / سلفة"/><Card><Text style={styles.hint}>إيرادات الطلاب لا تُضاف يدوياً؛ تنتقل آلياً من التحصيل.</Text><OptionPicker label="نوع المصروف" value={entryType} options={[['general','مصروف عام'],['salary','راتب موظف'],['advance','سلفة موظف'],['bonus','مكافأة'],['rent','إيجار'],['utility','مرافق'],['purchase','مشتريات']].map(([value,label])=>({value,label}))} onChange={setEntryType}/>{['salary','advance','bonus'].includes(entryType)?<OptionPicker label="الموظف" value={employee} options={staff.map(s=>({value:s.id,label:`${s.full_name} — ${s.role==='teacher'?'مدرس':s.role==='secretary'?'سكرتير':'مدير'}`}))} onChange={setEmployee} placeholder="اختر الموظف"/>:null}<AppInput label="التصنيف" value={category} onChangeText={setCategory} placeholder="مثال: راتب سبتمبر"/><AppInput label="المبلغ" value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/><AppInput label="الوصف" value={desc} onChangeText={setDesc}/><AppButton title="حفظ المصروف" icon="checkmark" variant="danger" onPress={save}/></Card><SectionTitle title="تحصيل كل موظف"/>{collectorTotals.map(([name,total])=><Card key={name} style={styles.row}><Text style={styles.title}>{name}</Text><Text style={styles.money}>{Number(total).toFixed(2)} جنيه محصل</Text></Card>)}<SectionTitle title="رواتب وسلفيات الموظفين"/>{employeeTotals.map(([id,total])=><Card key={id} style={styles.row}><Text style={styles.title}>{staff.find(s=>s.id===id)?.full_name||'موظف'}</Text><Text style={styles.money}>{Number(total).toFixed(2)} جنيه خلال السجل الحالي</Text></Card>)}<SectionTitle title="آخر الحركات"/><ScrollView>{rows.map(r=><Card key={r.id} style={styles.row}><Text style={styles.title}>{r.category} · {r.kind==='income'?'إيراد':'مصروف'}</Text><Text style={styles.meta}>{r.description||'بدون وصف'} · {r.occurred_on}</Text><Text style={[styles.money,{color:r.kind==='income'?colors.success:colors.danger}]}>{Number(r.amount).toFixed(2)} جنيه</Text><Text style={styles.by}>سجلها: {r.created_by_name||'—'}</Text></Card>)}</ScrollView></KeyboardScreen></GradientScreen>}
function Stat({t,v}:{t:string;v:number}){return <View><Text style={styles.meta}>{t}</Text><Text style={styles.stat}>{v.toFixed(0)} ج</Text></View>}
const styles=themedStyles(()=>StyleSheet.create({summary:{flexDirection:'row',justifyContent:'space-between'},stat:{color:colors.text,fontSize:font.lg,fontWeight:'900'},meta:{color:colors.textSecondary,fontSize:font.xs},hint:{color:colors.textSecondary,fontSize:font.sm,textAlign:'right',marginBottom:spacing.md},row:{marginBottom:spacing.sm},title:{color:colors.text,fontWeight:'800',textAlign:'right'},money:{fontSize:font.lg,fontWeight:'900',textAlign:'right'},by:{color:colors.textMuted,fontSize:font.xs,textAlign:'right',marginTop:4}}));
